version: "3.9"
services:
    authorization-server:
        build:
            context: .
            dockerfile: docker/springboot-server.Dockerfile
            args:
                appconfig: config/authorization-server.yml
                jarfile: authorization-server/build/authorization-server.jar
                port: 8080
        image: authorization-server
        ports:
            - "8080:8080"
        networks:
            - internal
        depends_on:
            - mysql-db
    resource-server:
        build:
            context: .
            dockerfile: docker/springboot-server.Dockerfile
            args:
                appconfig: config/resource-server.yml
                jarfile: resource-server/build/resource-server.jar
                port: 8081
        image: resource-server
        ports:
            - "8081:8081"
        networks:
            - internal
        depends_on:
            - mysql-db
            - authorization-server
    mysql-db:
        image: mysql:8
        networks:
            - internal
        environment:
            - MYSQL_DATABASE=authdb
            - MYSQL_ROOT_PASSWORD=root
networks:
    internal:
