# Data source & profile configuration
spring:
  datasource:
    url: jdbc:mysql://mysql-db:3306/authdb?createDatabaseIfNotExist=true
    username: root
    password: root
  profiles:                                  # The dev profile automatically creates default
    active: dev                              # entities to help manual testing.

# Settings related to this specific application
application:
  resource-servers:
    urls:                                    # If the base URL of a resource server registration request
      - http://localhost:8081                # is not whitelisted here, the request will be denied.
    user-token:
      lifespan: 60                           # The lifespan of user tokens issued to resource servers.
  scheduling:
    delete-expired-entities: 0 0/1 * * * ?   # Cron string - how often expired tokens are deleted.
  tokens:
    auth-code:                               # Lifespans of authorization codes,
      lifespan: 60                           # access tokens and refresh tokens.
    access-token:
      lifespan: 1800
    refresh-token:
      lifespan: 86400
    id-token:
      lifespan: 300

---

spring:
  config:
    activate:
      on-profile: dev
  sql:
    init:
      data-locations: classpath:data-dev.sql
