server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://mysql-db:3306/resourcedb?createDatabaseIfNotExist=true
    username: root
    password: root
application:
  authorization-server:
    url: 127.0.0.1
