server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://mysql-db:3306/resourcedb?createDatabaseIfNotExist=true
    username: root
    password: root
application:
  authorization-server:
    url: http://authorization-server:8080
    registration-endpoint: /oauth/resource
    authentication-endpoint: /oauth/resource/user
    user-login-endpoint: /user/login
