@file:Suppress("JpaAttributeTypeInspection")
package com.bme.jnsbbk.oauthserver.resource.entities

import com.bme.jnsbbk.oauthserver.utils.SpacedSetSerializer
import com.fasterxml.jackson.databind.annotation.JsonSerialize
import javax.persistence.Column
import javax.persistence.Entity
import javax.persistence.Id

/**
 * An entity class representing an OAuth resource server.
 *
 * Each resource server must have an ID and a secret, its own URL, and a set of associated scopes.
 * The ID and secret are securely generated by the authorization server, but the URL and the scope
 * entries are received from the resource server during registration.
 */
@Entity
data class ResourceServer(
    /** The ID of the resource server, used for authentication. Is unique. */
    @Id val id: String,
    /** The secret of the server, used for authentication. */
    val secret: String,
    /** The base URL of the server. Must be unique. */
    @Column(unique = true) val baseUrl: String,
    /** The set of scopes the resource server requests. */
    @JsonSerialize(using = SpacedSetSerializer::class) val scope: Set<String>
)
